esphome:
  name: temp-sensor
  friendly_name: temp_sensor
# Configuration for HTU21D Temperature & Humidity sensor
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

sensor:
  - platform: htu21d
    temperature:
      name: "HTU21D-01 Temperature"
      accuracy_decimals: 1
    humidity:
      name: "HTU21D-01 Humidity"
      accuracy_decimals: 1
    update_interval: 60s

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "placeholder"

ota:
  password: "placeholder"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Sensor Fallback Hotspot"
    password: "placeholder"

captive_portal:
