esphome:
  name: temp-sensor
  friendly_name: temp_sensor
# Configuration for HTU21D Temperature & Humidity sensor
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

mqtt:
  topic_prefix: sensor/1
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: status
    payload: 1
    retain: true
  will_message:
    topic: status
    payload: 0
    retain: true


sensor:
  - platform: htu21d
    temperature:
      name: "temp"
      accuracy_decimals: 1
    humidity:
      name: "humidity"
      accuracy_decimals: 1
 #   update_interval: 60s

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Sensor Fallback Hotspot"
    password: ""

deep_sleep:
  run_duration: 1min
  sleep_duration: 1min

captive_portal:
